// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: proto/kv.proto

package proto

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Err int32

const (
	Err_OK             Err = 0
	Err_Duplicate      Err = 1
	Err_ErrNoKey       Err = 2
	Err_ErrConflict    Err = 3
	Err_ErrClosed      Err = 4
	Err_ErrWrongLeader Err = 5
)

// Enum value maps for Err.
var (
	Err_name = map[int32]string{
		0: "OK",
		1: "Duplicate",
		2: "ErrNoKey",
		3: "ErrConflict",
		4: "ErrClosed",
		5: "ErrWrongLeader",
	}
	Err_value = map[string]int32{
		"OK":             0,
		"Duplicate":      1,
		"ErrNoKey":       2,
		"ErrConflict":    3,
		"ErrClosed":      4,
		"ErrWrongLeader": 5,
	}
)

func (x Err) Enum() *Err {
	p := new(Err)
	*p = x
	return p
}

func (x Err) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Err) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_kv_proto_enumTypes[0].Descriptor()
}

func (Err) Type() protoreflect.EnumType {
	return &file_proto_kv_proto_enumTypes[0]
}

func (x Err) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Err.Descriptor instead.
func (Err) EnumDescriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{0}
}

type MutationKind int32

const (
	MutationKind_Put    MutationKind = 0
	MutationKind_Append MutationKind = 1
	MutationKind_Delete MutationKind = 2
)

// Enum value maps for MutationKind.
var (
	MutationKind_name = map[int32]string{
		0: "Put",
		1: "Append",
		2: "Delete",
	}
	MutationKind_value = map[string]int32{
		"Put":    0,
		"Append": 1,
		"Delete": 2,
	}
)

func (x MutationKind) Enum() *MutationKind {
	p := new(MutationKind)
	*p = x
	return p
}

func (x MutationKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MutationKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_kv_proto_enumTypes[1].Descriptor()
}

func (MutationKind) Type() protoreflect.EnumType {
	return &file_proto_kv_proto_enumTypes[1]
}

func (x MutationKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MutationKind.Descriptor instead.
func (MutationKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{1}
}

type LockStatus int32

const (
	LockStatus_Locked     LockStatus = 0
	LockStatus_Commited   LockStatus = 1
	LockStatus_Rollbacked LockStatus = 2
)

// Enum value maps for LockStatus.
var (
	LockStatus_name = map[int32]string{
		0: "Locked",
		1: "Commited",
		2: "Rollbacked",
	}
	LockStatus_value = map[string]int32{
		"Locked":     0,
		"Commited":   1,
		"Rollbacked": 2,
	}
)

func (x LockStatus) Enum() *LockStatus {
	p := new(LockStatus)
	*p = x
	return p
}

func (x LockStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LockStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_kv_proto_enumTypes[2].Descriptor()
}

func (LockStatus) Type() protoreflect.EnumType {
	return &file_proto_kv_proto_enumTypes[2]
}

func (x LockStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LockStatus.Descriptor instead.
func (LockStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{2}
}

type Mutation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op    MutationKind `protobuf:"varint,1,opt,name=op,proto3,enum=shardkv.MutationKind" json:"op,omitempty"`
	Key   []byte       `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte       `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Mutation) Reset() {
	*x = Mutation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutation) ProtoMessage() {}

func (x *Mutation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutation.ProtoReflect.Descriptor instead.
func (*Mutation) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{0}
}

func (x *Mutation) GetOp() MutationKind {
	if x != nil {
		return x.Op
	}
	return MutationKind_Put
}

func (x *Mutation) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Mutation) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type GetArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetArgs) Reset() {
	*x = GetArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArgs) ProtoMessage() {}

func (x *GetArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArgs.ProtoReflect.Descriptor instead.
func (*GetArgs) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{1}
}

func (x *GetArgs) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetArgs) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err         Err    `protobuf:"varint,1,opt,name=err,proto3,enum=shardkv.Err" json:"err,omitempty"`
	Value       string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	LeaderIndex int32  `protobuf:"varint,3,opt,name=leader_index,json=leaderIndex,proto3" json:"leader_index,omitempty"`
}

func (x *GetReply) Reset() {
	*x = GetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kv_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReply) ProtoMessage() {}

func (x *GetReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReply.ProtoReflect.Descriptor instead.
func (*GetReply) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{2}
}

func (x *GetReply) GetErr() Err {
	if x != nil {
		return x.Err
	}
	return Err_OK
}

func (x *GetReply) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetReply) GetLeaderIndex() int32 {
	if x != nil {
		return x.LeaderIndex
	}
	return 0
}

type ModifyArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind  string `protobuf:"bytes,2,opt,name=Kind,proto3" json:"Kind,omitempty"`
	Key   string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ModifyArgs) Reset() {
	*x = ModifyArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kv_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyArgs) ProtoMessage() {}

func (x *ModifyArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyArgs.ProtoReflect.Descriptor instead.
func (*ModifyArgs) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{3}
}

func (x *ModifyArgs) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ModifyArgs) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ModifyArgs) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ModifyArgs) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ModifyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err         Err   `protobuf:"varint,1,opt,name=err,proto3,enum=shardkv.Err" json:"err,omitempty"`
	LeaderIndex int32 `protobuf:"varint,2,opt,name=leader_index,json=leaderIndex,proto3" json:"leader_index,omitempty"`
}

func (x *ModifyReply) Reset() {
	*x = ModifyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kv_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyReply) ProtoMessage() {}

func (x *ModifyReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyReply.ProtoReflect.Descriptor instead.
func (*ModifyReply) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{4}
}

func (x *ModifyReply) GetErr() Err {
	if x != nil {
		return x.Err
	}
	return Err_OK
}

func (x *ModifyReply) GetLeaderIndex() int32 {
	if x != nil {
		return x.LeaderIndex
	}
	return 0
}

type TxnGetArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StartTs uint64 `protobuf:"varint,2,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	Key     []byte `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *TxnGetArgs) Reset() {
	*x = TxnGetArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kv_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnGetArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnGetArgs) ProtoMessage() {}

func (x *TxnGetArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnGetArgs.ProtoReflect.Descriptor instead.
func (*TxnGetArgs) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{5}
}

func (x *TxnGetArgs) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TxnGetArgs) GetStartTs() uint64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *TxnGetArgs) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type TxnGetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err         Err    `protobuf:"varint,1,opt,name=err,proto3,enum=shardkv.Err" json:"err,omitempty"`
	LeaderIndex int32  `protobuf:"varint,2,opt,name=leader_index,json=leaderIndex,proto3" json:"leader_index,omitempty"`
	Value       []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *TxnGetReply) Reset() {
	*x = TxnGetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kv_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnGetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnGetReply) ProtoMessage() {}

func (x *TxnGetReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnGetReply.ProtoReflect.Descriptor instead.
func (*TxnGetReply) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{6}
}

func (x *TxnGetReply) GetErr() Err {
	if x != nil {
		return x.Err
	}
	return Err_OK
}

func (x *TxnGetReply) GetLeaderIndex() int32 {
	if x != nil {
		return x.LeaderIndex
	}
	return 0
}

func (x *TxnGetReply) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type TxnPrewriteArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StartTs     uint64      `protobuf:"varint,2,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	PrimaryLock []byte      `protobuf:"bytes,3,opt,name=primary_lock,json=primaryLock,proto3" json:"primary_lock,omitempty"`
	Mutations   []*Mutation `protobuf:"bytes,4,rep,name=mutations,proto3" json:"mutations,omitempty"`
}

func (x *TxnPrewriteArgs) Reset() {
	*x = TxnPrewriteArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kv_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnPrewriteArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnPrewriteArgs) ProtoMessage() {}

func (x *TxnPrewriteArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnPrewriteArgs.ProtoReflect.Descriptor instead.
func (*TxnPrewriteArgs) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{7}
}

func (x *TxnPrewriteArgs) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TxnPrewriteArgs) GetStartTs() uint64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *TxnPrewriteArgs) GetPrimaryLock() []byte {
	if x != nil {
		return x.PrimaryLock
	}
	return nil
}

func (x *TxnPrewriteArgs) GetMutations() []*Mutation {
	if x != nil {
		return x.Mutations
	}
	return nil
}

type TxnPrewriteReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err         Err   `protobuf:"varint,1,opt,name=err,proto3,enum=shardkv.Err" json:"err,omitempty"`
	LeaderIndex int32 `protobuf:"varint,2,opt,name=leader_index,json=leaderIndex,proto3" json:"leader_index,omitempty"`
}

func (x *TxnPrewriteReply) Reset() {
	*x = TxnPrewriteReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kv_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnPrewriteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnPrewriteReply) ProtoMessage() {}

func (x *TxnPrewriteReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnPrewriteReply.ProtoReflect.Descriptor instead.
func (*TxnPrewriteReply) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{8}
}

func (x *TxnPrewriteReply) GetErr() Err {
	if x != nil {
		return x.Err
	}
	return Err_OK
}

func (x *TxnPrewriteReply) GetLeaderIndex() int32 {
	if x != nil {
		return x.LeaderIndex
	}
	return 0
}

type TxnCommitArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StartTs  uint64   `protobuf:"varint,2,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	CommitTs uint64   `protobuf:"varint,3,opt,name=commit_ts,json=commitTs,proto3" json:"commit_ts,omitempty"`
	Keys     [][]byte `protobuf:"bytes,4,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *TxnCommitArgs) Reset() {
	*x = TxnCommitArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kv_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnCommitArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnCommitArgs) ProtoMessage() {}

func (x *TxnCommitArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnCommitArgs.ProtoReflect.Descriptor instead.
func (*TxnCommitArgs) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{9}
}

func (x *TxnCommitArgs) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TxnCommitArgs) GetStartTs() uint64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *TxnCommitArgs) GetCommitTs() uint64 {
	if x != nil {
		return x.CommitTs
	}
	return 0
}

func (x *TxnCommitArgs) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

type TxnCommitReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err         Err   `protobuf:"varint,1,opt,name=err,proto3,enum=shardkv.Err" json:"err,omitempty"`
	LeaderIndex int32 `protobuf:"varint,2,opt,name=leader_index,json=leaderIndex,proto3" json:"leader_index,omitempty"`
}

func (x *TxnCommitReply) Reset() {
	*x = TxnCommitReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kv_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnCommitReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnCommitReply) ProtoMessage() {}

func (x *TxnCommitReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnCommitReply.ProtoReflect.Descriptor instead.
func (*TxnCommitReply) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{10}
}

func (x *TxnCommitReply) GetErr() Err {
	if x != nil {
		return x.Err
	}
	return Err_OK
}

func (x *TxnCommitReply) GetLeaderIndex() int32 {
	if x != nil {
		return x.LeaderIndex
	}
	return 0
}

type TxnRollbackArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StartTs uint64   `protobuf:"varint,2,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	Keys    [][]byte `protobuf:"bytes,3,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *TxnRollbackArgs) Reset() {
	*x = TxnRollbackArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kv_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnRollbackArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnRollbackArgs) ProtoMessage() {}

func (x *TxnRollbackArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnRollbackArgs.ProtoReflect.Descriptor instead.
func (*TxnRollbackArgs) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{11}
}

func (x *TxnRollbackArgs) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TxnRollbackArgs) GetStartTs() uint64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *TxnRollbackArgs) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

type TxnRollbackReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err         Err   `protobuf:"varint,1,opt,name=err,proto3,enum=shardkv.Err" json:"err,omitempty"`
	LeaderIndex int32 `protobuf:"varint,2,opt,name=leader_index,json=leaderIndex,proto3" json:"leader_index,omitempty"`
}

func (x *TxnRollbackReply) Reset() {
	*x = TxnRollbackReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kv_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnRollbackReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnRollbackReply) ProtoMessage() {}

func (x *TxnRollbackReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnRollbackReply.ProtoReflect.Descriptor instead.
func (*TxnRollbackReply) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{12}
}

func (x *TxnRollbackReply) GetErr() Err {
	if x != nil {
		return x.Err
	}
	return Err_OK
}

func (x *TxnRollbackReply) GetLeaderIndex() int32 {
	if x != nil {
		return x.LeaderIndex
	}
	return 0
}

type TxnCheckStatusArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StartTs    uint64 `protobuf:"varint,2,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	PrimaryKey []byte `protobuf:"bytes,3,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
}

func (x *TxnCheckStatusArgs) Reset() {
	*x = TxnCheckStatusArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kv_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnCheckStatusArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnCheckStatusArgs) ProtoMessage() {}

func (x *TxnCheckStatusArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnCheckStatusArgs.ProtoReflect.Descriptor instead.
func (*TxnCheckStatusArgs) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{13}
}

func (x *TxnCheckStatusArgs) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TxnCheckStatusArgs) GetStartTs() uint64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *TxnCheckStatusArgs) GetPrimaryKey() []byte {
	if x != nil {
		return x.PrimaryKey
	}
	return nil
}

type TxnCheckStatusReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err         Err        `protobuf:"varint,1,opt,name=err,proto3,enum=shardkv.Err" json:"err,omitempty"`
	LeaderIndex int32      `protobuf:"varint,2,opt,name=leader_index,json=leaderIndex,proto3" json:"leader_index,omitempty"`
	LockStatus  LockStatus `protobuf:"varint,3,opt,name=lock_status,json=lockStatus,proto3,enum=shardkv.LockStatus" json:"lock_status,omitempty"`
}

func (x *TxnCheckStatusReply) Reset() {
	*x = TxnCheckStatusReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kv_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnCheckStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnCheckStatusReply) ProtoMessage() {}

func (x *TxnCheckStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnCheckStatusReply.ProtoReflect.Descriptor instead.
func (*TxnCheckStatusReply) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{14}
}

func (x *TxnCheckStatusReply) GetErr() Err {
	if x != nil {
		return x.Err
	}
	return Err_OK
}

func (x *TxnCheckStatusReply) GetLeaderIndex() int32 {
	if x != nil {
		return x.LeaderIndex
	}
	return 0
}

func (x *TxnCheckStatusReply) GetLockStatus() LockStatus {
	if x != nil {
		return x.LockStatus
	}
	return LockStatus_Locked
}

type ConfigQueryArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ConfigQueryArgs) Reset() {
	*x = ConfigQueryArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kv_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigQueryArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigQueryArgs) ProtoMessage() {}

func (x *ConfigQueryArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigQueryArgs.ProtoReflect.Descriptor instead.
func (*ConfigQueryArgs) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{15}
}

func (x *ConfigQueryArgs) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ConfigQueryReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err         Err      `protobuf:"varint,1,opt,name=err,proto3,enum=shardkv.Err" json:"err,omitempty"`
	Peers       []string `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	LeaderIndex int32    `protobuf:"varint,3,opt,name=leader_index,json=leaderIndex,proto3" json:"leader_index,omitempty"`
}

func (x *ConfigQueryReply) Reset() {
	*x = ConfigQueryReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kv_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigQueryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigQueryReply) ProtoMessage() {}

func (x *ConfigQueryReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigQueryReply.ProtoReflect.Descriptor instead.
func (*ConfigQueryReply) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{16}
}

func (x *ConfigQueryReply) GetErr() Err {
	if x != nil {
		return x.Err
	}
	return Err_OK
}

func (x *ConfigQueryReply) GetPeers() []string {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *ConfigQueryReply) GetLeaderIndex() int32 {
	if x != nil {
		return x.LeaderIndex
	}
	return 0
}

var File_proto_kv_proto protoreflect.FileDescriptor

var file_proto_kv_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6b, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x22, 0x59, 0x0a, 0x08, 0x4d, 0x75, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x15, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x2e, 0x4d, 0x75, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x2b, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x41, 0x72, 0x67, 0x73, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x22, 0x63, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1e, 0x0a,
	0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x73, 0x68, 0x61,
	0x72, 0x64, 0x6b, 0x76, 0x2e, 0x45, 0x72, 0x72, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6c, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x58, 0x0a, 0x0a, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79,
	0x41, 0x72, 0x67, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x50, 0x0a, 0x0b, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x1e, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x73,
	0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x2e, 0x45, 0x72, 0x72, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12,
	0x21, 0x0a, 0x0c, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x22, 0x49, 0x0a, 0x0a, 0x54, 0x78, 0x6e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x67, 0x73,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x66, 0x0a,
	0x0b, 0x54, 0x78, 0x6e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1e, 0x0a, 0x03,
	0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x73, 0x68, 0x61, 0x72,
	0x64, 0x6b, 0x76, 0x2e, 0x45, 0x72, 0x72, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x21, 0x0a, 0x0c,
	0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x90, 0x01, 0x0a, 0x0f, 0x54, 0x78, 0x6e, 0x50, 0x72, 0x65,
	0x77, 0x72, 0x69, 0x74, 0x65, 0x41, 0x72, 0x67, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x5f, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x54, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x5f,
	0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x70, 0x72, 0x69, 0x6d,
	0x61, 0x72, 0x79, 0x4c, 0x6f, 0x63, 0x6b, 0x12, 0x2f, 0x0a, 0x09, 0x6d, 0x75, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x68, 0x61,
	0x72, 0x64, 0x6b, 0x76, 0x2e, 0x4d, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6d,
	0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x55, 0x0a, 0x10, 0x54, 0x78, 0x6e, 0x50,
	0x72, 0x65, 0x77, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1e, 0x0a, 0x03,
	0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x73, 0x68, 0x61, 0x72,
	0x64, 0x6b, 0x76, 0x2e, 0x45, 0x72, 0x72, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x21, 0x0a, 0x0c,
	0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22,
	0x6b, 0x0a, 0x0d, 0x54, 0x78, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x41, 0x72, 0x67, 0x73,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x54, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x53, 0x0a, 0x0e,
	0x54, 0x78, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1e,
	0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x73, 0x68,
	0x61, 0x72, 0x64, 0x6b, 0x76, 0x2e, 0x45, 0x72, 0x72, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x21,
	0x0a, 0x0c, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x22, 0x50, 0x0a, 0x0f, 0x54, 0x78, 0x6e, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b,
	0x41, 0x72, 0x67, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x6b,
	0x65, 0x79, 0x73, 0x22, 0x55, 0x0a, 0x10, 0x54, 0x78, 0x6e, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61,
	0x63, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1e, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x2e, 0x45,
	0x72, 0x72, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6c,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x60, 0x0a, 0x12, 0x54, 0x78,
	0x6e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x41, 0x72, 0x67, 0x73,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x70,
	0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0a, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x4b, 0x65, 0x79, 0x22, 0x8e, 0x01, 0x0a,
	0x13, 0x54, 0x78, 0x6e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x1e, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0c, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x2e, 0x45, 0x72, 0x72, 0x52,
	0x03, 0x65, 0x72, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6c, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x34, 0x0a, 0x0b, 0x6c, 0x6f, 0x63, 0x6b, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x73,
	0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x21, 0x0a,
	0x0f, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x72, 0x67, 0x73,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x6b, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x1e, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0c, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x2e, 0x45, 0x72, 0x72, 0x52,
	0x03, 0x65, 0x72, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x2a, 0x5e, 0x0a,
	0x03, 0x45, 0x72, 0x72, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09,
	0x44, 0x75, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x45,
	0x72, 0x72, 0x4e, 0x6f, 0x4b, 0x65, 0x79, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x45, 0x72, 0x72,
	0x43, 0x6f, 0x6e, 0x66, 0x6c, 0x69, 0x63, 0x74, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x72,
	0x72, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x10, 0x04, 0x12, 0x12, 0x0a, 0x0e, 0x45, 0x72, 0x72,
	0x57, 0x72, 0x6f, 0x6e, 0x67, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x10, 0x05, 0x2a, 0x2f, 0x0a,
	0x0c, 0x4d, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x07, 0x0a,
	0x03, 0x50, 0x75, 0x74, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64,
	0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x10, 0x02, 0x2a, 0x36,
	0x0a, 0x0a, 0x4c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a, 0x06,
	0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x65, 0x64, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x64, 0x10, 0x02, 0x32, 0xa8, 0x04, 0x0a, 0x09, 0x4b, 0x76, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x09, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x47, 0x65,
	0x74, 0x12, 0x10, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x2e, 0x47, 0x65, 0x74, 0x41,
	0x72, 0x67, 0x73, 0x1a, 0x11, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x39, 0x0a, 0x0c, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x12, 0x13, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76,
	0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x14, 0x2e, 0x73, 0x68,
	0x61, 0x72, 0x64, 0x6b, 0x76, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x39, 0x0a, 0x0c, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x54, 0x78, 0x6e, 0x47, 0x65,
	0x74, 0x12, 0x13, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x2e, 0x54, 0x78, 0x6e, 0x47,
	0x65, 0x74, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x14, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76,
	0x2e, 0x54, 0x78, 0x6e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x48, 0x0a, 0x11,
	0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x54, 0x78, 0x6e, 0x50, 0x72, 0x65, 0x77, 0x72, 0x69, 0x74,
	0x65, 0x12, 0x18, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x2e, 0x54, 0x78, 0x6e, 0x50,
	0x72, 0x65, 0x77, 0x72, 0x69, 0x74, 0x65, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x19, 0x2e, 0x73, 0x68,
	0x61, 0x72, 0x64, 0x6b, 0x76, 0x2e, 0x54, 0x78, 0x6e, 0x50, 0x72, 0x65, 0x77, 0x72, 0x69, 0x74,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x42, 0x0a, 0x0f, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x54, 0x78, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x2e, 0x73, 0x68, 0x61, 0x72,
	0x64, 0x6b, 0x76, 0x2e, 0x54, 0x78, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x41, 0x72, 0x67,
	0x73, 0x1a, 0x17, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x2e, 0x54, 0x78, 0x6e, 0x43,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x48, 0x0a, 0x11, 0x48, 0x61,
	0x6e, 0x64, 0x6c, 0x65, 0x54, 0x78, 0x6e, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x12,
	0x18, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x2e, 0x54, 0x78, 0x6e, 0x52, 0x6f, 0x6c,
	0x6c, 0x62, 0x61, 0x63, 0x6b, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x19, 0x2e, 0x73, 0x68, 0x61, 0x72,
	0x64, 0x6b, 0x76, 0x2e, 0x54, 0x78, 0x6e, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x51, 0x0a, 0x14, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x54, 0x78,
	0x6e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x2e, 0x73,
	0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x2e, 0x54, 0x78, 0x6e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x1c, 0x2e, 0x73, 0x68, 0x61, 0x72,
	0x64, 0x6b, 0x76, 0x2e, 0x54, 0x78, 0x6e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x48, 0x0a, 0x11, 0x48, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x18, 0x2e, 0x73,
	0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x19, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76,
	0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x7a, 0x6a, 0x72, 0x65, 0x67, 0x65, 0x65, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_kv_proto_rawDescOnce sync.Once
	file_proto_kv_proto_rawDescData = file_proto_kv_proto_rawDesc
)

func file_proto_kv_proto_rawDescGZIP() []byte {
	file_proto_kv_proto_rawDescOnce.Do(func() {
		file_proto_kv_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_kv_proto_rawDescData)
	})
	return file_proto_kv_proto_rawDescData
}

var file_proto_kv_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_kv_proto_goTypes = []any{
	(Err)(0),                    // 0: shardkv.Err
	(MutationKind)(0),           // 1: shardkv.MutationKind
	(LockStatus)(0),             // 2: shardkv.LockStatus
	(*Mutation)(nil),            // 3: shardkv.Mutation
	(*GetArgs)(nil),             // 4: shardkv.GetArgs
	(*GetReply)(nil),            // 5: shardkv.GetReply
	(*ModifyArgs)(nil),          // 6: shardkv.ModifyArgs
	(*ModifyReply)(nil),         // 7: shardkv.ModifyReply
	(*TxnGetArgs)(nil),          // 8: shardkv.TxnGetArgs
	(*TxnGetReply)(nil),         // 9: shardkv.TxnGetReply
	(*TxnPrewriteArgs)(nil),     // 10: shardkv.TxnPrewriteArgs
	(*TxnPrewriteReply)(nil),    // 11: shardkv.TxnPrewriteReply
	(*TxnCommitArgs)(nil),       // 12: shardkv.TxnCommitArgs
	(*TxnCommitReply)(nil),      // 13: shardkv.TxnCommitReply
	(*TxnRollbackArgs)(nil),     // 14: shardkv.TxnRollbackArgs
	(*TxnRollbackReply)(nil),    // 15: shardkv.TxnRollbackReply
	(*TxnCheckStatusArgs)(nil),  // 16: shardkv.TxnCheckStatusArgs
	(*TxnCheckStatusReply)(nil), // 17: shardkv.TxnCheckStatusReply
	(*ConfigQueryArgs)(nil),     // 18: shardkv.ConfigQueryArgs
	(*ConfigQueryReply)(nil),    // 19: shardkv.ConfigQueryReply
}
var file_proto_kv_proto_depIdxs = []int32{
	1,  // 0: shardkv.Mutation.op:type_name -> shardkv.MutationKind
	0,  // 1: shardkv.GetReply.err:type_name -> shardkv.Err
	0,  // 2: shardkv.ModifyReply.err:type_name -> shardkv.Err
	0,  // 3: shardkv.TxnGetReply.err:type_name -> shardkv.Err
	3,  // 4: shardkv.TxnPrewriteArgs.mutations:type_name -> shardkv.Mutation
	0,  // 5: shardkv.TxnPrewriteReply.err:type_name -> shardkv.Err
	0,  // 6: shardkv.TxnCommitReply.err:type_name -> shardkv.Err
	0,  // 7: shardkv.TxnRollbackReply.err:type_name -> shardkv.Err
	0,  // 8: shardkv.TxnCheckStatusReply.err:type_name -> shardkv.Err
	2,  // 9: shardkv.TxnCheckStatusReply.lock_status:type_name -> shardkv.LockStatus
	0,  // 10: shardkv.ConfigQueryReply.err:type_name -> shardkv.Err
	4,  // 11: shardkv.KvService.HandleGet:input_type -> shardkv.GetArgs
	6,  // 12: shardkv.KvService.HandleModify:input_type -> shardkv.ModifyArgs
	8,  // 13: shardkv.KvService.HandleTxnGet:input_type -> shardkv.TxnGetArgs
	10, // 14: shardkv.KvService.HandleTxnPrewrite:input_type -> shardkv.TxnPrewriteArgs
	12, // 15: shardkv.KvService.HandleTxnCommit:input_type -> shardkv.TxnCommitArgs
	14, // 16: shardkv.KvService.HandleTxnRollback:input_type -> shardkv.TxnRollbackArgs
	16, // 17: shardkv.KvService.HandleTxnCheckStatus:input_type -> shardkv.TxnCheckStatusArgs
	18, // 18: shardkv.KvService.HandleConfigQuery:input_type -> shardkv.ConfigQueryArgs
	5,  // 19: shardkv.KvService.HandleGet:output_type -> shardkv.GetReply
	7,  // 20: shardkv.KvService.HandleModify:output_type -> shardkv.ModifyReply
	9,  // 21: shardkv.KvService.HandleTxnGet:output_type -> shardkv.TxnGetReply
	11, // 22: shardkv.KvService.HandleTxnPrewrite:output_type -> shardkv.TxnPrewriteReply
	13, // 23: shardkv.KvService.HandleTxnCommit:output_type -> shardkv.TxnCommitReply
	15, // 24: shardkv.KvService.HandleTxnRollback:output_type -> shardkv.TxnRollbackReply
	17, // 25: shardkv.KvService.HandleTxnCheckStatus:output_type -> shardkv.TxnCheckStatusReply
	19, // 26: shardkv.KvService.HandleConfigQuery:output_type -> shardkv.ConfigQueryReply
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_kv_proto_init() }
func file_proto_kv_proto_init() {
	if File_proto_kv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_kv_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Mutation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kv_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kv_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kv_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ModifyArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kv_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ModifyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kv_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*TxnGetArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kv_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*TxnGetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kv_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*TxnPrewriteArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kv_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*TxnPrewriteReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kv_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*TxnCommitArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kv_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*TxnCommitReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kv_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*TxnRollbackArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kv_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*TxnRollbackReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kv_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*TxnCheckStatusArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kv_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*TxnCheckStatusReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kv_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*ConfigQueryArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kv_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*ConfigQueryReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_kv_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_kv_proto_goTypes,
		DependencyIndexes: file_proto_kv_proto_depIdxs,
		EnumInfos:         file_proto_kv_proto_enumTypes,
		MessageInfos:      file_proto_kv_proto_msgTypes,
	}.Build()
	File_proto_kv_proto = out.File
	file_proto_kv_proto_rawDesc = nil
	file_proto_kv_proto_goTypes = nil
	file_proto_kv_proto_depIdxs = nil
}
